apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: davp-demo38-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: davp-demo38-1 
  name: davp-demo38-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: davp-demo38-1 
